### ISSUE TITLE
Option<u32> type broken in apply scenario

### ISSUE THREAD

**Issue by da-x** [jjpe/deltoid#2]
Hi,

In the example below quick-check created values that found an issue in applying a delta. This kind of test can be extended to more complex types for arbitrary-generated values.

```
Thread 'main' panicked at '[quickcheck] TEST FAILED. Arguments: (Basic { field: Some(38) }, Basic { first_symbol: None })', /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.8.5/src/tester.rs:176:28
```

```rust
use deltoid::{Delta, Apply};
use deltoid_derive::Delta;
use quickcheck::quickcheck;
use quickcheck_derive::Arbitrary;
use serde_derive::{Deserialize, Serialize};

#[derive(Clone, Eq, PartialEq, PartialOrd, Ord, Debug, Delta, Serialize, Deserialize, Arbitrary)]
pub struct Basic {
    pub field: Option<u32>,
}

fn tester(a: Basic, b: Basic) -> bool {
    let delta = a.delta(&b).unwrap();
    let c = a.apply(delta).unwrap();
    return b == c;
}

fn main() {
    quickcheck(tester as fn(Basic, Basic) -> bool);
}
```

Example dependencies:

```toml
[dependencies]
deltoid = { git = "https://github.com/jjpe/deltoid" }
deltoid-derive = { git = "https://github.com/jjpe/deltoid" }
serde_derive = "1"
serde = "1"
quickcheck = "0.8"
quickcheck_macros = "0.8"
quickcheck_derive = "*"
rand = "0.6"
```
